### ISSUE TITLE
ERROR (MainThread) [supervisor.jobs] Unhandled exception: Remote 'origin' has no refspec set

### ISSUE THREAD

**Issue by jach0012** [home-assistant/supervisor#3592]
### Describe the issue you are experiencing

When I try to update the add-on store repositories, the following git problem appears.
"ERROR (MainThread) [supervisor.jobs] Unhandled exception: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'."

### What is the used version of the Supervisor?

supervisor-2022.04.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

8.0.rc1

### What version of Home Assistant Core is installed?

core-2022.4.6

### Steps to reproduce the issue

1. Settings
2. Add-Ons...
3. Add-On-Store
4. Check for updates
...

### Anything in the Supervisor logs that might be useful for us?

```txt
22-04-24 15:17:30 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 876, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 835, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
22-04-24 15:17:31 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2275' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 876, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 835, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 112, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
22-04-24 15:17:32 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/aiohttp.py", line 121, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/aiohttp.py", line 111, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 139, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 205, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 65, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/addons.py", line 162, in list
    data_addons = [
  File "/usr/src/supervisor/supervisor/api/addons.py", line 164, in <listcomp>
    ATTR_NAME: addon.name,
  File "/usr/src/supervisor/supervisor/addons/model.py", line 135, in name
    return self.data[ATTR_NAME]
  File "/usr/src/supervisor/supervisor/store/addon.py", line 19, in data
    return self.sys_store.data.addons[self.slug]
KeyError: 'a0d7b954_logviewer'
22-04-24 15:17:32 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 0 new - 0 remove
22-04-24 15:17:32 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 0 new - 0 remove
```

**Comment by zuldero** [comment]
if i try to execute this command it dont work as far as i can tell.
![image](https://user-images.githubusercontent.com/40671412/165116846-fd8cf5cc-5dfa-4522-86c2-7ec466eee032.png)

**Comment by mdegat01** [comment]
That log isn't actually telling you to run that command. Supervisor uses the git cli under the hood to pull and clone add-on repositories. When something is wrong the git cli gives errors like that trying to tell the human that it assumes is running the command to do something. But you running it from some random other location won't do anything except maybe mess something else up.

From the cli if you run `ha addons reload` what happens? Do you still see those errors? If so then next lets try `ha supervisor repair`. It seems like the git repos in supervisor's filesystem has become corrupted so between those two it should fix it. If not let me know and we'll have to see what else we can try.

**Comment by jach0012** [comment]
Hi mdegat01. I run both commands and restartet the supervisor and tried to update the add-on repositories.
The problem is still there.


| |  | |                          /\           (_)   | |            | |
| |__| | ___  _ __ ___   ___     /  \   ___ ___ _ ___| |_ __ _ _ __ | |_
|  __  |/ _ \| '_ \ _ \ / _ \   / /\ \ / __/ __| / __| __/ _\ | '_ \| __|
| |  | | (_) | | | | | |  __/  / ____ \\__ \__ \ \__ \ || (_| | | | | |_
|_|  |_|\___/|_| |_| |_|\___| /_/    \_\___/___/_|___/\__\__,_|_| |_|\__|

Welcome to the Home Assistant command line.

System information
  IPv4 addresses for eth0:  192.168.178.107/24
  IPv6 addresses for eth0:  2a02:6d40:3084:6301:7287:c0d:947e:8c3a/64, fe80::9669:837b:2e39:f1ea/64

  OS Version:               Home Assistant OS 8.0.rc1
  Home Assistant Core:      2022.4.7

  Home Assistant URL:       http://homeassistant.local:8123
  Observer URL:             http://homeassistant.local:4357
➜  ~ ha addons reload
Processing... Done.

Command completed successfully.
➜  ~ ha addons repair
addons:
- advanced: false
  available: true
  build: false
  description: A local NTP (Network Time Protocol) server for cameras etc.
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: chrony
  repository: a0d7b954
  slug: a0d7b954_chrony
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-chrony
  version: null
  version_latest: 2.3.0
- advanced: false
  available: true
  build: false
  description: Fast, modern, secure VPN tunnel
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: WireGuard
  repository: a0d7b954
  slug: a0d7b954_wireguard
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-wireguard
  version: null
  version_latest: 0.6.0
- advanced: false
  available: true
  build: false
  description: Network-wide ads & trackers blocking DNS server
  detached: false
  homeassistant: 0.113.2
  icon: true
  installed: false
  logo: true
  name: AdGuard Home
  repository: a0d7b954
  slug: a0d7b954_adguard
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-adguard-home
  version: null
  version_latest: 4.5.1
- advanced: false
  available: true
  build: false
  description: AirPlay capabilities for your Sonos (and UPnP) devices.
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: AirSonos
  repository: a0d7b954
  slug: a0d7b954_airsonos
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-airsonos
  version: null
  version_latest: 3.3.0
- advanced: false
  available: true
  build: false
  description: Fully configurable Z-Wave JS to MQTT gateway and control panel; based
    on Zwavejs2Mqtt
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Z-Wave JS to MQTT
  repository: a0d7b954
  slug: a0d7b954_zwavejs2mqtt
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-zwavejs2mqtt
  version: null
  version_latest: 0.38.0
- advanced: false
  available: true
  build: false
  description: AirPlay capabilities for your Chromecast devices.
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: AirCast
  repository: a0d7b954
  slug: a0d7b954_aircast
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-aircast
  version: null
  version_latest: 3.3.0
- advanced: false
  available: true
  build: false
  description: Simple & Free Wiki Software
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Bookstack
  repository: a0d7b954
  slug: a0d7b954_bookstack
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-bookstack
  version: null
  version_latest: 1.0.2
- advanced: false
  available: true
  build: false
  description: Protect your privacy and access Home Assistant via Tor.
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Tor
  repository: a0d7b954
  slug: a0d7b954_tor
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-tor
  version: null
  version_latest: 3.0.5
- advanced: true
  available: true
  build: false
  description: SSH & Web Terminal access to your Home Assistant instance
  detached: false
  homeassistant: 0.92.0b2
  icon: true
  installed: true
  logo: true
  name: SSH & Web Terminal
  repository: a0d7b954
  slug: a0d7b954_ssh
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-ssh
  version: 10.1.2
  version_latest: 10.1.2
- advanced: false
  available: true
  build: false
  description: Manage Nginx proxy hosts with a simple, powerful interface
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Nginx Proxy Manager
  repository: a0d7b954
  slug: a0d7b954_nginxproxymanager
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-nginx-proxy-manager
  version: null
  version_latest: 0.11.0
- advanced: false
  available: true
  build: false
  description: A cross-platform system monitoring tool
  detached: false
  homeassistant: 0.92.0b2
  icon: true
  installed: false
  logo: true
  name: Glances
  repository: a0d7b954
  slug: a0d7b954_glances
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-glances
  version: null
  version_latest: 0.15.0
- advanced: false
  available: true
  build: false
  description: Play Spotify music on your Home Assistant device
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Spotify Connect
  repository: a0d7b954
  slug: a0d7b954_spotify
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-spotify-connect
  version: null
  version_latest: 0.11.0
- advanced: true
  available: true
  build: false
  description: Explore your SQLite database
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: SQLite Web
  repository: a0d7b954
  slug: a0d7b954_sqlite-web
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-sqlite-web/tree/main/README.md
  version: null
  version_latest: 3.3.0
- advanced: false
  available: true
  build: false
  description: DEPRECATED - ESPHome
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: ESPHome
  repository: a0d7b954
  slug: a0d7b954_esphome
  stage: deprecated
  update_available: false
  url: https://esphome.io/
  version: null
  version_latest: 2022.3.1
- advanced: false
  available: true
  build: false
  description: Example add-on by Community Home Assistant Add-ons
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Example
  repository: a0d7b954
  slug: a0d7b954_example
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-example
  version: null
  version_latest: 4.5.0
- advanced: false
  available: true
  build: false
  description: Simple, elegant and feature-rich CCTV/NVR for your cameras
  detached: false
  homeassistant: 0.92.0b2
  icon: true
  installed: true
  logo: true
  name: motionEye
  repository: a0d7b954
  slug: a0d7b954_motioneye
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-motioneye
  version: 0.18.0
  version_latest: 0.18.0
- advanced: false
  available: true
  build: false
  description: ERP beyond your fridge! A groceries & household management solution
    for your home
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Grocy
  repository: a0d7b954
  slug: a0d7b954_grocy
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-grocy
  version: null
  version_latest: 0.17.0
- advanced: false
  available: true
  build: false
  description: The open platform for beautiful analytics and monitoring
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Grafana
  repository: a0d7b954
  slug: a0d7b954_grafana
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-grafana
  version: null
  version_latest: 7.5.2
- advanced: false
  available: false
  build: false
  description: Fighting disease with a world wide distributed super computer
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Folding@home
  repository: a0d7b954
  slug: a0d7b954_foldingathome
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-foldingathome
  version: null
  version_latest: 0.5.0
- advanced: false
  available: true
  build: false
  description: Browser-based log utility for Home Assistant
  detached: false
  homeassistant: 0.92.0b2
  icon: true
  installed: false
  logo: true
  name: Log Viewer
  repository: a0d7b954
  slug: a0d7b954_logviewer
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-log-viewer
  version: null
  version_latest: 0.13.0
- advanced: false
  available: true
  build: false
  description: Fully featured Visual Studio Code (VSCode) experience integrated in
    the Home Assistant frontend.
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Studio Code Server
  repository: a0d7b954
  slug: a0d7b954_vscode
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-vscode
  version: null
  version_latest: 5.0.1
- advanced: false
  available: true
  build: false
  description: Modern GPS Tracking Platform
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Traccar
  repository: a0d7b954
  slug: a0d7b954_traccar
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-traccar
  version: null
  version_latest: 0.16.0
- advanced: false
  available: true
  build: false
  description: A web frontend for controlling the home
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Home Panel
  repository: a0d7b954
  slug: a0d7b954_home-panel
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-home-panel
  version: null
  version_latest: 2.4.0
- advanced: false
  available: true
  build: false
  description: HomeMatic/homematicIP CCU central based on RaspberryMatic (Snapshot)
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: RaspberryMatic CCU (snapshot)
  repository: de838cd8
  slug: de838cd8_raspberrymatic-dev
  stage: experimental
  update_available: false
  url: https://github.com/jens-maus/RaspberryMatic/
  version: null
  version_latest: 3.63.9.20220430-a39bf92
- advanced: false
  available: true
  build: false
  description: Monitoring and tracking tool for Plex Media Server
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Tautulli
  repository: a0d7b954
  slug: a0d7b954_tautulli
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-tautulli/tree/main/README.md
  version: null
  version_latest: 2.3.0
- advanced: false
  available: true
  build: false
  description: HomeMatic/homematicIP CCU central based on RaspberryMatic
  detached: false
  homeassistant: null
  icon: true
  installed: true
  logo: true
  name: RaspberryMatic CCU
  repository: de838cd8
  slug: de838cd8_raspberrymatic
  stage: stable
  update_available: false
  url: https://github.com/jens-maus/RaspberryMatic/
  version: 3.63.8.20220330
  version_latest: 3.63.8.20220330
- advanced: false
  available: true
  build: false
  description: Manage your UniFi network using a web browser
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: UniFi Network Application
  repository: a0d7b954
  slug: a0d7b954_unifi
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-unifi
  version: null
  version_latest: 2.1.1
- advanced: false
  available: true
  build: false
  description: Recorded media, live TV, online news, and podcasts ready to stream.
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Plex Media Server
  repository: a0d7b954
  slug: a0d7b954_plex
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-plex
  version: null
  version_latest: 2.8.0
- advanced: false
  available: true
  build: false
  description: Centrally manage all your Sonoff-Tasmota devices
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: TasmoAdmin
  repository: a0d7b954
  slug: a0d7b954_sonweb
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-tasmoadmin
  version: null
  version_latest: 0.17.0
- advanced: false
  available: true
  build: false
  description: Open source password management solution
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Vaultwarden (Bitwarden)
  repository: a0d7b954
  slug: a0d7b954_bitwarden
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-bitwarden
  version: null
  version_latest: 0.16.0
- advanced: false
  available: true
  build: false
  description: Zero config VPN for building secure networks
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Tailscale
  repository: a0d7b954
  slug: a0d7b954_tailscale
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-tailscale
  version: null
  version_latest: 0.6.1
- advanced: false
  available: true
  build: false
  description: A self-hosted web IRC client
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: The Lounge
  repository: a0d7b954
  slug: a0d7b954_thelounge
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-thelounge
  version: null
  version_latest: 0.14.0
- advanced: false
  available: true
  build: false
  description: Manage battery backup (UPS) devices
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: Network UPS Tools
  repository: a0d7b954
  slug: a0d7b954_nut
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-nut
  version: null
  version_latest: 0.10.0
- advanced: false
  available: true
  build: false
  description: A secure and fast FTP server for Home Assistant
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: FTP
  repository: a0d7b954
  slug: a0d7b954_ftp
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-ftp
  version: null
  version_latest: 4.5.0
- advanced: false
  available: true
  build: false
  description: Scalable datastore for metrics, events, and real-time analytics
  detached: false
  homeassistant: 0.92.0b2
  icon: true
  installed: false
  logo: true
  name: InfluxDB
  repository: a0d7b954
  slug: a0d7b954_influxdb
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-influxdb
  version: null
  version_latest: 4.4.1
- advanced: false
  available: true
  build: false
  description: A web interface for the official MariaDB add-on
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: phpMyAdmin
  repository: a0d7b954
  slug: a0d7b954_phpmyadmin
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-phpmyadmin
  version: null
  version_latest: 0.7.1
- advanced: false
  available: true
  build: false
  description: A secure and decentralized communication platform.
  detached: false
  homeassistant: 0.92.0b2
  icon: true
  installed: false
  logo: true
  name: Matrix
  repository: a0d7b954
  slug: a0d7b954_matrix
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-matrix
  version: null
  version_latest: 0.10.0
- advanced: false
  available: true
  build: false
  description: Create documents containing live code, equations, visualizations, and
    explanatory text
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: JupyterLab
  repository: a0d7b954
  slug: a0d7b954_jupyterlablite
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-jupyterlab
  version: null
  version_latest: 0.7.0
- advanced: false
  available: true
  build: false
  description: Flow-based programming for the Internet of Things
  detached: false
  homeassistant: 2021.3.0
  icon: true
  installed: true
  logo: true
  name: Node-RED
  repository: a0d7b954
  slug: a0d7b954_nodered
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-node-red
  version: 11.1.1
  version_latest: 11.1.1
- advanced: false
  available: true
  build: false
  description: Radically simplify your network with a virtual networking layer that
    works the same everywhere
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: ZeroTier One
  repository: a0d7b954
  slug: a0d7b954_zerotier
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-zerotier
  version: null
  version_latest: 0.13.2
- advanced: false
  available: true
  build: false
  description: Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
  detached: false
  homeassistant: null
  icon: true
  installed: false
  logo: true
  name: AppDaemon
  repository: a0d7b954
  slug: a0d7b954_appdaemon
  stage: stable
  update_available: false
  url: https://github.com/hassio-addons/addon-appdaemon
  version: null
  version_latest: 0.8.2
repositories:
- maintainer: you
  name: Local add-ons
  slug: local
  source: local
  url: https://home-assistant.io/hassio
- maintainer: Home Assistant
  name: Official add-ons
  slug: core
  source: core
  url: https://home-assistant.io/addons
- maintainer: Franck Nijhof <frenck@addons.community>
  name: Home Assistant Community Add-ons
  slug: a0d7b954
  source: https://github.com/hassio-addons/repository
  url: https://addons.community
- maintainer: RaspberryMatic Team <mail@raspberrymatic.de>
  name: Home Assistant RaspberryMatic Add-on
  slug: de838cd8
  source: https://github.com/jens-maus/RaspberryMatic
  url: https://github.com/jens-maus/RaspberryMatic/
➜  ~

LOG:
22-04-30 10:42:51 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/jens-maus/RaspberryMatic repository
22-04-30 10:42:51 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-04-30 10:42:51 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-04-30 10:42:51 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.

**Comment by zuldero** [comment]
for me pretty simular. i just get a "Processing... Done." and nothing happens, on both commands.

**Comment by mdegat01** [comment]
@jach0012 the second command I suggested was `ha supervisor repair`. It looks like you did `ha addons repair` which isn't a command (that's why it just listed all your addons as output).

@zuldero did you also do `ha addons repair` or did you do `ha supervisor repair`?

**Comment by zuldero** [comment]
i run all the commands and nothing saddly changed.

**Comment by jach0012** [comment]
sorry for the misunderstanding.
Like zuldero I only get "Processing... Done." with "ha supervisor repair"
Logs:
22-05-01 20:42:24 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-05-01 20:42:24 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-05-01 20:42:24 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-05-01 20:42:24 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-05-01 20:42:24 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-05-01 20:42:24 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-05-01 20:42:24 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-05-01 20:42:24 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-05-01 20:42:24 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-05-01 20:42:24 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-05-01 20:44:41 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-05-01 21:14:42 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-05-01 21:42:24 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-05-01 21:42:24 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-05-01 21:42:24 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-05-01 21:42:24 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-05-01 21:42:24 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-05-01 21:42:24 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-05-01 21:42:24 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-05-01 21:42:24 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-05-01 21:42:24 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-05-01 21:42:24 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-05-01 21:42:24 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-05-01 21:42:24 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-05-01 21:44:42 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-05-01 21:45:45 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
22-05-01 21:45:45 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
22-05-01 21:45:45 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from a0d7b954_ssh
22-05-01 21:45:45 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from a0d7b954_ssh
22-05-01 21:46:12 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/repair access from a0d7b954_ssh
22-05-01 21:46:12 INFO (MainThread) [supervisor.core] Starting repair of Supervisor Environment
22-05-01 21:46:12 INFO (SyncWorker_0) [supervisor.docker] Prune stale containers
22-05-01 21:46:17 INFO (SyncWorker_0) [supervisor.docker] Prune stale images
22-05-01 21:46:19 INFO (SyncWorker_0) [supervisor.docker] Prune stale builds
22-05-01 21:46:19 INFO (SyncWorker_0) [supervisor.docker] Prune stale volumes
22-05-01 21:46:19 INFO (SyncWorker_0) [supervisor.docker] Prune stale networks
22-05-01 21:46:19 INFO (SyncWorker_0) [supervisor.docker] Fix stale container on hassio network
22-05-01 21:46:19 INFO (SyncWorker_0) [supervisor.docker] Fix stale container on host network
22-05-01 21:46:19 INFO (MainThread) [supervisor.addons] Found 1 add-ons to repair
22-05-01 21:46:19 INFO (MainThread) [supervisor.addons] Repairing for add-on: a0d7b954_nodered
22-05-01 21:46:19 INFO (SyncWorker_2) [supervisor.docker.interface] Downloading docker image ghcr.io/hassio-addons/node-red/aarch64 with tag 11.1.1.
22-05-01 21:47:04 INFO (MainThread) [supervisor.supervisor] Repairing Supervisor 2022.04.0
22-05-01 21:47:04 INFO (MainThread) [supervisor.core] Finished repair of Supervisor Environment
22-05-01 21:47:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/jens-maus/RaspberryMatic repository
22-05-01 21:47:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-05-01 21:47:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-05-01 21:47:11 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 876, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 835, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
22-05-01 21:47:12 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-63014' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 876, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 835, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 112, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
22-05-01 21:47:13 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 0 new - 0 remove
22-05-01 21:47:13 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 0 new - 0 remove

**Comment by zuldero** [comment]
ou true a log i forgot.... secont time i run ``ha supervisor repair`` i got this log 
```
22-05-01 21:55:04 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/repair access from core_ssh
22-05-01 21:55:04 INFO (MainThread) [supervisor.core] Starting repair of Supervisor Environment
22-05-01 21:55:04 INFO (SyncWorker_3) [supervisor.docker] Prune stale containers
22-05-01 21:55:04 INFO (SyncWorker_3) [supervisor.docker] Prune stale images
22-05-01 21:55:04 INFO (SyncWorker_3) [supervisor.docker] Prune stale builds
22-05-01 21:55:04 INFO (SyncWorker_3) [supervisor.docker] Prune stale volumes
22-05-01 21:55:04 INFO (SyncWorker_3) [supervisor.docker] Prune stale networks
22-05-01 21:55:05 INFO (SyncWorker_3) [supervisor.docker] Fix stale container on hassio network
22-05-01 21:55:05 INFO (SyncWorker_3) [supervisor.docker] Fix stale container on host network
22-05-01 21:55:05 INFO (MainThread) [supervisor.addons] Found 0 add-ons to repair
22-05-01 21:55:05 INFO (MainThread) [supervisor.supervisor] Repairing Supervisor 2022.04.2
22-05-01 21:55:05 INFO (MainThread) [supervisor.core] Finished repair of Supervisor Environment
```
but still nothing changed

**Comment by zuldero** [comment]
i loaded the backup on a new installation. and it was fixed. mayby the sd card was damaged

**Comment by djecot** [comment]
Im get this error  

File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 205, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 65, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/addons.py", line 162, in list
    data_addons = [
  File "/usr/src/supervisor/supervisor/api/addons.py", line 164, in <listcomp>
    ATTR_NAME: addon.name,
  File "/usr/src/supervisor/supervisor/addons/model.py", line 135, in name
    return self.data[ATTR_NAME]
  File "/usr/src/supervisor/supervisor/store/addon.py", line 19, in data
    return self.sys_store.data.addons[self.slug]
KeyError: 'db21ed7f_webtrees'
22-06-25 01:25:42 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/aiohttp.py", line 121, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/aiohttp.py", line 111, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 139, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 205, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 65, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/store.py", line 120, in store_info
    ATTR_ADDONS: [
  File "/usr/src/supervisor/supervisor/api/store.py", line 121, in <listcomp>
    self._generate_addon_information(self.sys_addons.store[addon])
  File "/usr/src/supervisor/supervisor/api/store.py", line 81, in _generate_addon_information
    ATTR_ADVANCED: addon.advanced,
  File "/usr/src/supervisor/supervisor/addons/model.py", line 222, in advanced
    return self.data[ATTR_ADVANCED]
  File "/usr/src/supervisor/supervisor/store/addon.py", line 19, in data
    return self.sys_store.data.addons[self.slug]
KeyError: 'a0d7b954_glances'
