### ISSUE TITLE
Update of Supervisor failed version 2024.11.3

### ISSUE THREAD

**Issue by jverlaan** [home-assistant/supervisor#5405]
**:information_source: :information_source: :information_source:  We understand what the issue is and are working on a solution. Please be patient. For now, please ignore any warnings about having an "unhealthy" supervisor.  :information_source: :information_source: :information_source:**  

For more background, please read [this comment](https://github.com/home-assistant/supervisor/issues/5405#issuecomment-2468565190).

### Describe the issue you are experiencing

Home Assistant Supervisor
Installed version 2024.11.2
Latest version 2024.11.3

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:49:21 AM (2 occurrences)
Last logged: 9:49:51 AM

[140507219199600] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 262, in async_install
    await self.coordinator.supervisor_client.supervisor.update()
  File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/supervisor.py", line 43, in update
    await self._client.post(
  File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/client.py", line 173, in post
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/client.py", line 122, in _request
    raise exc_type(result.message, result.job_id)
aiohasupervisor.exceptions.SupervisorBadRequestError: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 18µs, allowed: 44000/minute")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 502, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 264, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 18µs, allowed: 44000/minute")

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Updates says there is a Supervisor Update
2. Start installing the update
3. After a few seconds the error messages apairs
...

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-11-11 06:37:37.504 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-11-11 06:37:37.509 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-11-11 06:37:37.510 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-11-11 06:40:50.358 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-11-11 07:10:50.911 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-11-11 07:17:55.523 INFO (MainThread) [supervisor.host.info] Updating local host information
2024-11-11 07:17:56.644 INFO (MainThread) [supervisor.host.services] Updating service information
2024-11-11 07:17:56.668 INFO (MainThread) [supervisor.host.network] Updating local network information
2024-11-11 07:17:57.312 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
2024-11-11 07:17:57.331 INFO (MainThread) [supervisor.host.manager] Host information reload completed
2024-11-11 07:37:01.454 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-11-11 07:37:37.514 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-11-11 07:37:37.516 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-11-11 07:37:37.520 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system
2024-11-11 07:37:37.529 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-11-11 07:37:37.531 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-11-11 07:37:37.533 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-11-11 07:37:37.542 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-11-11 07:37:37.580 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-11-11 07:37:37.582 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-11-11 07:37:37.583 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system
2024-11-11 07:37:37.584 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-11-11 07:37:37.588 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-11-11 07:37:37.589 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-11-11 07:37:37.590 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-11-11 07:37:38.022 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-11-11 07:37:38.023 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-11-11 07:37:38.023 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-11-11 07:38:27.814 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/thomasmauerer/hassio-addons repository
2024-11-11 07:38:27.829 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/music-assistant/home-assistant-addon repository
2024-11-11 07:38:27.837 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
2024-11-11 07:38:27.848 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
2024-11-11 07:38:27.862 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
2024-11-11 07:38:30.903 INFO (MainThread) [supervisor.store] Loading add-ons from store: 81 all - 0 new - 0 remove
2024-11-11 07:38:30.903 INFO (MainThread) [supervisor.store] Loading add-ons from store: 81 all - 0 new - 0 remove
2024-11-11 07:40:51.377 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-11-11 08:10:51.959 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-11-11 08:37:38.026 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-11-11 08:37:38.026 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-11-11 08:37:38.027 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system
2024-11-11 08:37:38.027 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-11-11 08:37:38.097 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-11-11 08:37:38.100 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-11-11 08:37:38.104 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-11-11 08:37:38.118 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-11-11 08:37:38.120 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-11-11 08:37:38.120 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system
2024-11-11 08:37:38.121 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-11-11 08:37:38.122 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-11-11 08:37:38.122 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-11-11 08:37:38.122 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-11-11 08:37:38.422 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-11-11 08:37:38.424 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-11-11 08:37:38.424 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-11-11 08:40:52.540 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-11-11 09:10:54.124 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-11-11 09:24:37.333 INFO (MainThread) [supervisor.host.info] Updating local host information
2024-11-11 09:24:38.415 INFO (MainThread) [supervisor.host.services] Updating service information
2024-11-11 09:24:38.431 INFO (MainThread) [supervisor.host.network] Updating local network information
2024-11-11 09:24:38.797 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
2024-11-11 09:24:38.821 INFO (MainThread) [supervisor.host.manager] Host information reload completed
2024-11-11 09:37:01.628 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-11-11 09:37:01.783 INFO (MainThread) [supervisor.misc.tasks] Found new Supervisor version 2024.11.3, updating
2024-11-11 09:37:01.784 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor_stable.txt
2024-11-11 09:37:01.838 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
2024-11-11 09:37:02.173 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2024.11.3
2024-11-11 09:37:02.175 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/amd64-hassio-supervisor with tag 2024.11.3.
2024-11-11 09:37:12.419 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")
2024-11-11 09:37:12.420 INFO (MainThread) [supervisor.resolution.module] Create new issue update_failed - supervisor / None
2024-11-11 09:37:12.479 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")
2024-11-11 09:37:38.426 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-11-11 09:37:38.428 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-11-11 09:37:38.429 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system
2024-11-11 09:37:38.431 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-11-11 09:37:38.432 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-11-11 09:37:38.433 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-11-11 09:37:38.435 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-11-11 09:37:38.464 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-11-11 09:37:38.468 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-11-11 09:37:38.469 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system
2024-11-11 09:37:38.471 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-11-11 09:37:38.475 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-11-11 09:37:38.478 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-11-11 09:37:38.481 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-11-11 09:37:38.797 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-11-11 09:37:38.798 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-11-11 09:37:38.798 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-11-11 09:40:54.771 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-11-11 09:49:20.149 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor_stable.txt
2024-11-11 09:49:20.280 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
2024-11-11 09:49:20.494 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2024.11.3
2024-11-11 09:49:20.495 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/amd64-hassio-supervisor with tag 2024.11.3.
2024-11-11 09:49:21.428 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 18µs, allowed: 44000/minute")
2024-11-11 09:49:21.502 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 18µs, allowed: 44000/minute")
2024-11-11 09:49:38.610 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor_stable.txt
2024-11-11 09:49:38.720 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
2024-11-11 09:49:38.940 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2024.11.3
2024-11-11 09:49:38.943 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/amd64-hassio-supervisor with tag 2024.11.3.
2024-11-11 09:49:51.084 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")
2024-11-11 09:49:51.109 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")
```

## System Information

version | core-2024.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1461
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 56.0 GB
disk_used | 20.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Studio Code Server (5.17.3), MariaDB (2.7.1), Terminal & SSH (9.15.0), Duck DNS (1.18.0), NGINX Home Assistant SSL proxy (3.11.0), InfluxDB (5.0.1), Grafana (10.1.3), Tailscale (0.23.2), Samba Backup (5.2.0), Dnsmasq (1.8.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 1
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 1, 2024 at 9:43 AM
-- | --
current_recorder_run | November 9, 2024 at 1:08 PM
estimated_db_size | 1245.77 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Supervisor diagnostics

Is HA OS. See first comment.

**Comment by Fidelity88** [comment]
Same issue, same error! Also using Home Assistant OS

**Comment by ketzerkadaver** [comment]
Same problem here!

**Comment by agners** [comment]
> Internal Server Error ("toomanyrequests: retry-after: 18µs, allowed: 44000/minute")

It seems we hit some type of rate limiting :thinking: . This likely will resolve after a while.

**Comment by Pussy123a** [comment]
Same problem here!

**Comment by eddysteurs** [comment]
me too

**Comment by sirlamoid** [comment]
Same problem here

**Comment by minmaxat** [comment]
same here, dont think that it is a rate limit:

Die Aktion update/install konnte nicht ausgeführt werden. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")

**Comment by adamprice56** [comment]
Same issue here, Running HAOS 13.2 and core version 2024.10.3

Just tried pulling the image from another (Non HA) machine and it shows "too many requests". This looks to be a server side/github issue. I guess the 404 is HA checking if the image is already downloaded?

**Comment by Fidelity88** [comment]
Indeed, it's not related to rate limiting. If you visit the URL of the error log multiple times (from the same network/IP), you will notice that you get the same rate limiting error:
https://ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3

But when you do not, it links to the github page with images. I guess the required image is missing for some reason. HASSOS keeps trying to get that image, which results in rate limiting.

**Comment by Pinni3** [comment]
Same issue here

**Comment by N8schatten** [comment]
Same Problem

**Comment by kgiedrius** [comment]
Failed to perform the action update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")

**Comment by Bloodpack** [comment]
same here

**Comment by YameChan** [comment]
same here

**Comment by TorstenHamper** [comment]
+1
same error message like all above.
Duplicated with https://github.com/home-assistant/supervisor/issues/5406

**Comment by Otiel** [comment]
No fix yet, stop replying with "same here", but simply add a 👍 to the original issue, this will stop spamming those of us who subscribed to the issue. 

Wait for the team to fix this, you probably have no rush updating Supervisor.

**Comment by fourmonks** [comment]
Same issue.

**Comment by garv3** [comment]
Same for me!

**Comment by Pinni3** [comment]
Actie update/install kon niet worden uitgevoerd. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 1.203566ms, allowed: 44000/minute")

**Comment by pickonedev** [comment]
Same issue. Now I even get this...

![image](https://github.com/user-attachments/assets/856b5998-7eda-40a2-b7b3-7f364c984e07)

**Comment by SimplYDeadgamer** [comment]
Same for me.
ao too many requests or no image.

**Comment by werfpsa** [comment]
Same issue for me!

**Comment by mstaffa** [comment]
Same here. HAOS 13.2, core 2024.9.3, failed to install the new supervisor.

**Comment by RockFlare** [comment]
Same issue.

**Comment by rama31244** [comment]
Same error 
Failed to perform the action update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")

**Comment by drorya1** [comment]
Same here 
Failed to perform the action update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")

**Comment by palsbo** [comment]
Same problem

**Comment by TheHuskyCrobats** [comment]
Same issue

**Comment by fwartner** [comment]
Same over here. Thought its ratelimited because of a service in my homelab.. Seems i was wrong ^^

**Comment by KirovAir** [comment]
`Failed to perform the action update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")
`

It seems the request limit is hit since this update is needed to update home-assistant core. 44000 downloads / minute is quite a high threshold so maybe Github is having some internal issues.

**Comment by Diegocampy** [comment]
Same 🙊

**Comment by jverlaan** [comment]
Please READ the comments!!!!
No fix yet, stop replying with "same here", but simply add a 👍 to the original issue, this will stop spamming those of us who subscribed to the issue.

Wait for the team to fix this, you probably have no rush updating Supervisor.

https://github.com/home-assistant/supervisor/issues/5405#issuecomment-2467668127

**Comment by kurdybanek** [comment]
So it is not my system malfunctioning, but some general error. Some sort a good information ;)

**Comment by RenZan** [comment]
even by avoiding the requests limit, the tag image is not present it seems.

**Comment by DrDonoso** [comment]
Please @

> No fix yet, stop replying with "same here", but simply add a 👍 to the original issue, this will stop spamming those of us who subscribed to the issue.
> 
> Wait for the team to fix this, you probably have no rush updating Supervisor.

Friendly reminder for everyone, please stop adding comments.

Please @owners, lock the conversation 😊.

**Comment by jpawlowski** [comment]
> even by avoiding the requests limit, the tag image is not present it seems.

Got pulled already which makes sense for this situation.

**Comment by novotechsoftware** [comment]
I think I just have bad timing because I moved from my VM HA setup to a NUC. Is there a way to continue installing things from the add-ons? Need to setup DuckDNS etc. but stuck now lol. Any way past this or do I just have to wait.

**Comment by fierens** [comment]
Same issue here

**Comment by Stephen2615** [comment]
Not wanting to add to the endless same here comment but I think my system was attempting to update the supervisor and something happened during the process. I have the message: **Unhealthy system - Supervisor update failed**, Is this the same as the unable to update the supervisor?

**Comment by Soulfly999** [comment]
Same with generic-x86-64

**Comment by droyls** [comment]
Same issue: 
Failed to perform the action update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")

**Comment by ComPeter33** [comment]
I'm new to Home Assistant, having just started using it a week ago. It's great to see such a large, supportive community offering helpful information and explanations.

I got this error 
{"errors":[{"code":"TOOMANYREQUESTS","message":"retry-after: 273.019µs, allowed: 44000/minute"}]}

**Comment by sempreinsieme** [comment]
I join the community with the same error.

Internal Server Error ("toomanyrequests: retry-after: 337.123µs, allowed: 44000/minute")

**Comment by nturbin** [comment]
Too many attenpts @ComPeter33, @sempreinsieme  Just wait and retry. But it's not usefull because the problem is not solved yet.

**Comment by szflo** [comment]
+1

**Comment by Friedel-weber** [comment]
Problem besteht:
Die Aktion update/install konnte nicht ausgeführt werden. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-supervisor&platform=linux%2Farm64: Internal Server Error ("toomanyrequests: retry-after: 711.858µs, allowed: 44000/minute")

**Comment by outpurst** [comment]
das problem habe ich ebenso

**Comment by AndrewsHappy** [comment]
Phew... glad I am not the only one having a problem. So I guess we wait until some bright spark puts right what ever the problem is....

**Comment by fernandolcardoso** [comment]
Is there any solution for this case? Home Assistant is blocking Add-on installations and I cannot update Supervisor due to the error imposed by the "toomanyrequests" error

![image](https://github.com/user-attachments/assets/7c2382e2-2d44-4ee9-9f68-8b20b5c61d2b)

![image](https://github.com/user-attachments/assets/0b82da70-0de2-4376-a7ff-96d4501af132)

![image](https://github.com/user-attachments/assets/19808e09-4b1f-41e8-b99b-72e034a3f5eb)

**Comment by jomavic** [comment]
Error during the update on Raspberry Pi5 64:
"Failed to perform the action update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")"

**Comment by vip-klaus** [comment]
Same problem here.

**Comment by spanzetta** [comment]
same here

**Comment by BowlerHatMen** [comment]
same here

**Comment by ErnestoBrandao** [comment]
same :(

**Comment by st-pavel** [comment]
same

**Comment by nco1512** [comment]
same here

**Comment by fhammel** [comment]
same

**Comment by jf-uu** [comment]
Replying "same" will not get the issue fixed any faster. It is clear that this is a wide-spread issue - if you're experiencing it then please just leave a :+1: on the issue instead of replying, as otherwise you notify every person subscribed to this issue.

**Comment by brietman** [comment]
> Is there any solution for this case? Home Assistant is blocking Add-on installations and I cannot update Supervisor due to the error imposed by the "toomanyrequests" error
> 
> ![image](https://private-user-images.githubusercontent.com/16019127/384894773-7c2382e2-2d44-4ee9-9f68-8b20b5c61d2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjQwNTAsIm5iZiI6MTczMTMyMzc1MCwicGF0aCI6Ii8xNjAxOTEyNy8zODQ4OTQ3NzMtN2MyMzgyZTItMmQ0NC00ZWU5LTlmNjgtOGIyMGI1YzYxZDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExMTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YjllMGViMjU1MDNiYzg3MWY2N2U4OTdiYjAzZjBjNjFmNTE5N2IzY2MxYzBiNmU2YmQ1MTY0M2M2NTQzYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6pM0JQ7HD0f80EE5TNpM1E1GVpCvOP-p1-7wIOplJPY)
> 
> ![image](https://private-user-images.githubusercontent.com/16019127/384894868-0b82da70-0de2-4376-a7ff-96d4501af132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjQwNTAsIm5iZiI6MTczMTMyMzc1MCwicGF0aCI6Ii8xNjAxOTEyNy8zODQ4OTQ4NjgtMGI4MmRhNzAtMGRlMi00Mzc2LWE3ZmYtOTZkNDUwMWFmMTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExMTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYmE4Yjc0ZDdlOTg3YjlhZmIxYWJmNzAwMzdlYTk4YTMzYThhYWNiZDNjM2NmMzAxNjEyMGJjYzgwYzg5YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VOLL8fCKdpV4GrenhOfZSasaTj3BgQN_EhPGTXUAt90)
> 
> ![image](https://private-user-images.githubusercontent.com/16019127/384894955-19808e09-4b1f-41e8-b99b-72e034a3f5eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjQwNTAsIm5iZiI6MTczMTMyMzc1MCwicGF0aCI6Ii8xNjAxOTEyNy8zODQ4OTQ5NTUtMTk4MDhlMDktNGIxZi00MWU4LWI5OWItNzJlMDM0YTNmNWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExMTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNjkwMTVlNTJlYTQ3NmQ2OGI0ZTkzMzhjNDU4YzIzYWZhNzg2MDc2NWI3MjAzYTJlYTFjZWMwZmUwMDg5ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RLIlEds1PKKJ4DTEpJH6aUZQU5AWDQUBk45f06b4txE)
> 
> `Error log: ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")`

If I am correct, this issue is caused by an buggy update process and trying to re-download? This marks HA-systems as "critical", causing to not wanting to update or install new add-ons. Isn't this unwanted behavior? Especially when this bugs stays for a longer period.

**Comment by Dubblbindong** [comment]
Same error as mentioned above

**Comment by fausthome** [comment]
Same error

2024-11-11 12:09:24.773 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-supervisor&platform=linux%2Farm64: Internal Server Error ("toomanyrequests: retry-after: 743.538µs, allowed: 44000/minute")
2024-11-11 12:09:24.773 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-supervisor&platform=linux%2Farm64: Internal Server Error ("toomanyrequests: retry-after: 743.538µs, allowed: 44000/minute")

2024-11-11 12:30:12.318 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")

**Comment by DrDonoso** [comment]
Making it bigger for those people...

![image](https://github.com/user-attachments/assets/fc5e79b6-da57-4fb5-aa3a-206e8b88de4d)

It's a common problem, please wait for the dev team.

**Comment by N3m3515** [comment]
> Making it bigger for those people...
> 
> ![image](https://private-user-images.githubusercontent.com/34934002/384901158-fc5e79b6-da57-4fb5-aa3a-206e8b88de4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjU0NjAsIm5iZiI6MTczMTMyNTE2MCwicGF0aCI6Ii8zNDkzNDAwMi8zODQ5MDExNTgtZmM1ZTc5YjYtZGE1Ny00ZmI1LWFhM2EtMjA2ZThiODhkZTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExMzkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZjNlMTM4NGI3MThlODQzYmUwZjgxY2Q4NWVkZGMwNDRiMDI2ZTc5M2VmMmJhZGUwYTkwYjY0NDM1NjYwN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IjJfYGu4d3kBoa7WajjNxA4gy0GYYJV1fKdOoQnDs9Q)
> 
> It's a common problem, please wait for the dev team.

The HA Devs condition you to reply by timing out issues that get no responses for a long time even tho they still excist

**Comment by brietman** [comment]
> Making it bigger for those people...
> 
> ![image](https://private-user-images.githubusercontent.com/34934002/384901158-fc5e79b6-da57-4fb5-aa3a-206e8b88de4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjU2MjMsIm5iZiI6MTczMTMyNTMyMywicGF0aCI6Ii8zNDkzNDAwMi8zODQ5MDExNTgtZmM1ZTc5YjYtZGE1Ny00ZmI1LWFhM2EtMjA2ZThiODhkZTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExNDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiOWZlNDk5ZTRlZTRmMWZhZTVmNDkwODcyMmU5YWIxNWQ2YzQzZTYyOGM3OWZkYzU0ODdiZWIxZTRjMTRjMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2AoCGG39n4oc_Z9BFKsGbRxzhsl6kAscw067dPIY890)
> 
> It's a common problem, please wait for the dev team.

SAME

**Comment by moongear** [comment]
Oh, and I am having the SAME problem, so ME TOO.  ;)

**Comment by jf-uu** [comment]
@moongear people are subscribed here to be notified when a fix is available - please do enlighten us on another way to be notified of this without being notified by all of the useless "same" replies.

**Comment by jf-uu** [comment]
@spanzetta I disagree:
![image](https://github.com/user-attachments/assets/bf6b1e3d-107e-4645-a23a-2bb1c70da60e)

**Comment by sanderkooger** [comment]
> > Replying "same" or posting the error you're getting will not get the issue fixed any faster. It is clear that this is a wide-spread issue and everyone is seeing the same error - if you're experiencing it then please just leave a 👍 on the issue instead of replying, as otherwise you notify every person subscribed to this issue.
> 
> adding a comment is the easiest way to get notified for new posts (subscribe)..

it's the best way to make sure everyone is notified that you are notified. Just press the subscribe button.  Give the OG post a thumbs up instead of making a you problem an everyone's problem.

**Comment by jf-uu** [comment]
TIL you out you can subscribe to just close notifications, seems like the best option:
![image](https://github.com/user-attachments/assets/408b5bb6-5d5a-45da-b6ba-b751c7f4961e)

**Comment by sanderkooger** [comment]
> TIL you out you can subscribe to just close notifications, seems like the best option: ![image](https://private-user-images.githubusercontent.com/181011550/384913635-408b5bb6-5d5a-45da-b6ba-b751c7f4961e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjcwMjUsIm5iZiI6MTczMTMyNjcyNSwicGF0aCI6Ii8xODEwMTE1NTAvMzg0OTEzNjM1LTQwOGI1YmI2LTVkNWEtNDVkYS1iNmJhLWI3NTFjN2Y0OTYxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMjA1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmZkZGIxZWM4Zjk5NWNjODM2NTFkODA0OTBkYmMwM2U5YmQ4NDViZGUwMjE1MDQ2N2NmOTI2ZWQ0YTBkMTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UltgQBIOyHNUHhpcG0kwQ1YYYnP5AY4RuAbBjA51JrI)

@jf-uu What are you not understanding. Please elaborate why everyone needs to be notified that you are now subscribed? Instead of getting notified of possible solutions, What is the thing that makes you so incredible important. And what makes you so self-important that instead of taking the hint that people do not like that behavior to encourage it?

**Comment by moongear** [comment]
> TIL you out you can subscribe to just close notifications, seems like the best option: ![image](https://private-user-images.githubusercontent.com/181011550/384913635-408b5bb6-5d5a-45da-b6ba-b751c7f4961e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjcxOTAsIm5iZiI6MTczMTMyNjg5MCwicGF0aCI6Ii8xODEwMTE1NTAvMzg0OTEzNjM1LTQwOGI1YmI2LTVkNWEtNDVkYS1iNmJhLWI3NTFjN2Y0OTYxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMjA4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTQ2NmZhN2E5YmI2MTk2NGVmMjQwYzFjZTAwY2NiODk5YTJkYzhmNzQwZGQ4MTJiNGFhYWI0OTllOTExMGI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mIChVTkz4_KZqdpWA5ysoKqHEwMEMix51wa5JNtnlXk)

This is good information.  Thanks for sharing.

**Comment by chino-lu** [comment]
> > > No fix yet, stop replying with "same here", but simply add a 👍 to the original issue, this will stop spamming those of us who subscribed to the issue.
> > > Wait for the team to fix this, you probably have no rush updating Supervisor.
> > 
> > 
> > Friendly reminder for everyone, please stop adding comments.
> > Please owners, lock the conversation 😊.
> 
> Those that do not want to get "spammed" could simply unsubscribe from this thread. In a bit of irony, your posts demanding that people stop posting are spamming others. So..... there's that. Should I make a big sign that reads, "UNSUBSCRIBE IF YOU DO NOT WANT TO RECEIVE NOTIFICATIONS WHEN SOMEONE REPIES TO THIS THREAD BECAUSE YOU WILL GET AN EMAIL ALERT AND IT WILL CAUSE YOU UNNECESSARY FRUSTRATION THAT COULD EASILY BE AVOIDED!" I mean, that'll teach ya, right?

And how are you alerted when it is solved?

**Comment by agners** [comment]
**What happened**

We changed the Supervisor update a while ago  to make Supervisor update as soon as it learns about the update (see https://github.com/home-assistant/supervisor/pull/5375). This was an intentional change, which has been tested since a couple of weeks, and rolled out already last week to stable.

Today's release was the first time where this new update mechanism got used when we published a new version to stable. The update had the side effect that updates rolled out within a 2h window (instead of 8h window), which was not handled well by the GitHub container registry (causing all the `toomanyrequests`).

**What is the fix**

The latest version of Supervisor has been pulled from Supervisor about 2h ago, which means that you should no longer see the update notification. So for most users, the errors in the logs should stop from appearing and the update notification disappears on it's own.

For users who have rebooted the system in the last ~8h they also see a message "Unhealthy system - Supervisor update failed". This message appears because despite a good network connection, we were not able to update the Supervisor. Another reboot of the system should make this message to appear as well.

**What if I updated successfully**

If you successfully updated to Supervisor 2024.11.3, that is fine too. The version itself is fine. The system won't rollback. We'll eventually release a new version of Supervisor so you'll have the same stable version as anyone else.

**What happens from now**

We are currently working on solutions to rollout the new Supervisor version without hitting the rate limit.

**Comment by simondrake** [comment]
Thanks @agners

**Comment by jj123451** [comment]
I restarted the HA, but still have the message when trying to install addons. Not sure if there is something I should do, or need to wait for the rollout soultion you are working on.
`Failed to to call /addons/9074a9fa_cloudflared/install - 'AddonManager.install' blocked from execution, system is not healthy - supervisor`

**Comment by jj123451** [comment]
> I was in the same case, rebooting just the core left me unable to update an add-on, but rebooting ha OS did the trick
It worked - thank you!

**Comment by Dubblbindong** [comment]
For my case its working again - Thank you

**Comment by BwezB** [comment]
Hi, after restarting my yellow multiple times, im still getting the message "'AddonManager.install' blocked from execution, system is not healthy - supervisor"
Does anyone have any ideas for a solution?

**Comment by Poltinnik650** [comment]
Я так же не могу войти в систему... Ну что за проблемы?..

**Comment by Acalanum** [comment]
I seem to still be having this issue I believe...maybe I'm in the wrong spot...

Trying to update to Core 2024.11.0 

In the supervisor logs, I'm getting this:

2024-11-11 15:48:02.130 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/qemux86-64-homeassistant:2024.11.0: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.0&fromImage=ghcr.io%2Fhome-assistant%2Fqemux86-64-homeassistant&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)")

Things I've tried:
Removed HACS completely (thought that was an issue)
Restarted Home assistant
rebooted VM that Home assistant runs on via Proxmox

Unfortunately still get this message.  If this is unrelated to this thread, could someone point me to the right spot?

Thanks!

**Comment by smarthomefamilyverrips** [comment]
> I seem to still be having this issue I believe...maybe I'm in the wrong spot...
> 
> Trying to update to Core 2024.11.0
> 
> In the supervisor logs, I'm getting this:
> 
> 2024-11-11 15:48:02.130 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/qemux86-64-homeassistant:2024.11.0: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.0&fromImage=ghcr.io%2Fhome-assistant%2Fqemux86-64-homeassistant&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)")
> 
> Things I've tried: Removed HACS completely (thought that was an issue) Restarted Home assistant rebooted VM that Home assistant runs on via Proxmox
> 
> Unfortunately still get this message. If this is unrelated to this thread, could someone point me to the right spot?
> 
> Thanks!

@Acalanum that is a Home Assistant Core issue not a supervisor issue and are most likely not related,  you can post your issue here https://github.com/home-assistant/core/issues

**Comment by alexlopezit** [comment]
> I was in the same case, rebooting just the core left me unable to update an add-on, but rebooting ha OS did the trick
Thanks, this worked for me too and I can now update other depending addons

I ran the reboot from the VM console (I use Proxmox) doing:

`host reboot`

**Comment by jgate** [comment]
I have this issue during Supervisor update to 2024.11.3

2024-11-11 12:28:02.043 INFO (MainThread) [__main__] Running Supervisor
2024-11-11 12:28:02.054 INFO (MainThread) [supervisor.os.manager] Rauc: slot B - activated slot kernel.1, marked slot kernel.1 as good
2024-11-11 12:28:02.061 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor_stable.txt
2024-11-11 12:28:02.130 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
2024-11-11 12:28:02.195 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2024.11.3
2024-11-11 12:28:02.195 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/amd64-hassio-supervisor with tag 2024.11.3.
2024-11-11 12:28:14.567 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")
2024-11-11 12:28:14.568 INFO (MainThread) [supervisor.resolution.module] Create new issue update_failed - supervisor / None
2024-11-11 12:28:14.592 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")
2024-11-11 12:28:14.592 CRITICAL (MainThread) [supervisor.core] Can't update Supervisor! This will break some Add-ons or affect future versions of Home Assistant!
2024-11-11 12:28:14.606 INFO (MainThread) [supervisor.addons.manager] Phase 'initialize' starting 0 add-ons
2024-11-11 12:28:14.610 INFO (MainThread) [supervisor.addons.manager] Phase 'system' starting 2 add-ons
2024-11-11 12:28:14.866 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.4.1
2024-11-11 12:28:15.103 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/tasmoadmin/amd64 with version 0.30.6
2024-11-11 12:28:17.360 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
2024-11-11 12:28:45.202 INFO (MainThread) [supervisor.addons.manager] Phase 'services' starting 8 add-ons



2024-11-11 12:29:59.497 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
2024-11-11 12:29:59.503 INFO (MainThread) [supervisor.host.manager] Host information reload completed
2024-11-11 12:30:24.852 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor_stable.txt
2024-11-11 12:30:25.007 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
2024-11-11 12:30:25.062 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2024.11.3
2024-11-11 12:30:25.062 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/amd64-hassio-supervisor with tag 2024.11.3.
2024-11-11 12:30:25.807 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 573.992µs, allowed: 44000/minute")
2024-11-11 12:30:25.812 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 573.992µs, allowed: 44000/minute")
2024-11-11 12:34:56.675 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
2024-11-11 12:34:57.241 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
2024-11-11 12:38:25.675 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor_stable.txt
2024-11-11 12:38:25.866 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
2024-11-11 12:38:25.919 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2024.11.3
2024-11-11 12:38:25.919 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/amd64-hassio-supervisor with tag 2024.11.3.
2024-11-11 12:38:27.614 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")
2024-11-11 12:38:27.639 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")
2024-11-11 12:39:57.252 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
2024-11-11 12:39:57.834 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
2024-11-11 12:44:57.628 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
2024-11-11 12:44:58.019 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
2


2024-11-12 11:54:58.934 INFO (MainThread) [supervisor.jobs] 'Tasks._update_cli' blocked from execution, system is not healthy - supervisor
2024-11-12 11:57:15.814 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
2024-11-12 11:57:16.359 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
2024-11-12 12:00:21.295 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-11-12 12:01:03.555 WARNING (MainThread) [supervisor.jobs] 'AddonManager.update' blocked from execution, system is not healthy - supervisor
2024-11-12 12:01:45.199 INFO (MainThread) [supervisor.backups.manager] Found 90 backup files
2024-11-12 12:02:16.269 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
2024-11-12 12:02:16.763 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
2024-11-12 12:02:31.069 INFO (MainThread) [supervisor.backups.manager] Found 90 backup files
2024-11-12 12:07:16.572 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup


![image](https://github.com/user-attachments/assets/c7ac9feb-ce8d-4a30-b7a2-2c8006773bb2)

**Comment by agners** [comment]
You largely can disregard any errors related to container updates in the time frame between 2024-11-11 09:32 and 14:55 GMT+1. This was during the problematic roll out attempt of Supervisor 2024.11.3. The rate limit applies for the whole Home Assistant organization, this means as a side effect during this time frame also other updates were affected (e.g. Core updates).

If your system is still marked unhealthy due to this incident, please read the solutions posted above (essentially, make sure you reboot the host or at least the Supervisor). If despite reboots unhealthy issues remains for you, is unlikely related to this particular rollout issue.

If you see `Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")` or similar issues after the above timeframe, this as well is unlikely related to this incident the ghcr.io infrastructure is back in regular operation. These are often local or provider specific issues. Please open a separate issue if you still believe this is a Supervisor fault.

If in doubt, use our community forum, e.g. for discussions around this issue there is [already a thread](https://community.home-assistant.io/t/cannot-install-supervisor-2024-11-3-hassos/793231).

I am locking that issue to avoid the relevant comments getting burried. Please use the community forum, feel free to tag me there if something needs my attention, or open a new issue here in the Supervisor issue tracker.

**Comment by agners** [comment]
With the rollout of 2024.11.4 this has been resolved at the end of last month already.

Note that this particular issue was about 2024.11.3 specifically, which showed `Internal Server Error ("toomanyrequests: retry-after: 18µs, allowed: 44000/minute")`. Other Supervisor update errors such as:

```
Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.x.y ...  Internal Server Error ("Get "https://ghcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

are *not* related to this issue. These are typically DNS or network issue.
