### ISSUE TITLE
Default mDNS settings results in network flooding in networks with reflectors enabled

### ISSUE THREAD

**Issue by sle118** [home-assistant/supervisor#5435]
### Describe the issue you are experiencing

The default NetworkManager configuration sets mDNS to `yes` which, in network having multiple vlans and a reflector (e.g. on a Unifi network), result in a flood of mDNS requests originating from the supervisor's systemd-resolved. I believe the network configuration originates from this line:
https://github.com/home-assistant/supervisor/blame/4e0de93096dc69c257056b36eff0c19b47006850/supervisor/dbus/network/setting/generate.py#L167

Typical flooding would look like this
```
2024-11-19 15:09:05.941 homeassistant systemd-resolved[416]: Hostname conflict, changing published hostname from 'homeassistant12746' to 'homeassistant12749'.
2024-11-19 15:09:06.214 homeassistant systemd-resolved[416]: Detected conflict on homeassistant12749\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN TXT ""
2024-11-19 15:09:06.214 homeassistant systemd-resolved[416]: Detected conflict on homeassistant12749\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN SRV 0 0 0 homeassistant12749.local
2024-11-19 15:09:06.214 homeassistant systemd-resolved[416]: Detected conflict on homeassistant12749.local IN A 192.168.10.247
2024-11-19 15:09:06.214 homeassistant systemd-resolved[416]: Hostname conflict, changing published hostname from 'homeassistant12749' to 'homeassistant12758'.
2024-11-19 15:09:06.450 homeassistant systemd-resolved[416]: Detected conflict on homeassistant12758\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN TXT ""
2024-11-19 15:09:06.451 homeassistant systemd-resolved[416]: Detected conflict on homeassistant12758\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN SRV 0 0 0 homeassistant12758.local
2024-11-19 15:09:06.451 homeassistant systemd-resolved[416]: Detected conflict on homeassistant12758.local IN A 192.168.10.247
2024-11-19 15:09:06.451 homeassistant systemd-resolved[416]: Hostname conflict, changing published hostname from 'homeassistant12758' to 'homeassistant12764'.
2024-11-19 15:09:06.704 homeassistant systemd-resolved[416]: Detected conflict on homeassistant12764\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN SRV 0 0 0 homeassistant12764.local
2024-11-19 15:09:06.704 homeassistant systemd-resolved[416]: Detected conflict on homeassistant12764\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN TXT ""
2024-11-19 15:09:06.704 homeassistant systemd-resolved[416]: Detected conflict on homeassistant12764.local IN A 192.168.10.247
2024-11-19 15:09:06.704 homeassistant systemd-resolved[416]: Hostname conflict, changing published hostname from 'homeassistant12764' to 'homeassistant12767'.
```

The issue was also reported under the operating system project, but got closed. Nevertheless, a long discussion continued after the issue got closed, with some hints on how to fix the issue.
https://github.com/home-assistant/operating-system/issues/1163#issuecomment-1817014802

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Run Home-Assistant on a network with multiple vlans
2. Setup a mDNS reflector to reflect mDNS packets across vlans 
3. Open the system->logs->host (http://homeassistant.local:8123/config/logs?provider=host)
4. Watch for systemd-resolved name collision entries in the log
...

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-11-19 15:00:45.209 homeassistant systemd-resolved[416]: Hostname conflict, changing published hostname from 'homeassistant11362' to 'homeassistant11363'.
2024-11-19 15:00:45.281 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11363\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN SRV 0 0 0 homeassistant11363.local
2024-11-19 15:00:45.281 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11363\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN TXT ""
2024-11-19 15:00:45.281 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11363\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN TXT ""
2024-11-19 15:00:45.281 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11363\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN SRV 0 0 0 homeassistant11363.local
2024-11-19 15:00:45.281 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11363.local IN A 192.168.10.247
2024-11-19 15:00:45.281 homeassistant systemd-resolved[416]: Hostname conflict, changing published hostname from 'homeassistant11363' to 'homeassistant11371'.
2024-11-19 15:00:45.453 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11371\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN SRV 0 0 0 homeassistant11371.local
2024-11-19 15:00:45.453 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11371\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN TXT ""
2024-11-19 15:00:45.453 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11371.local IN A 192.168.10.247
2024-11-19 15:00:45.453 homeassistant systemd-resolved[416]: Hostname conflict, changing published hostname from 'homeassistant11371' to 'homeassistant11381'.
2024-11-19 15:00:45.515 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11381\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN TXT ""
2024-11-19 15:00:45.515 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11381\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN SRV 0 0 0 homeassistant11381.local
2024-11-19 15:00:45.515 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11381.local IN A 192.168.10.247
2024-11-19 15:00:45.515 homeassistant systemd-resolved[416]: Hostname conflict, changing published hostname from 'homeassistant11381' to 'homeassistant11382'.
2024-11-19 15:00:45.734 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11382\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN TXT ""
2024-11-19 15:00:45.734 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11382\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN SRV 0 0 0 homeassistant11382.local
2024-11-19 15:00:45.735 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11382.local IN A 192.168.10.247
2024-11-19 15:00:45.735 homeassistant systemd-resolved[416]: Hostname conflict, changing published hostname from 'homeassistant11382' to 'homeassistant11386'.
2024-11-19 15:00:45.812 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11386\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN SRV 0 0 0 homeassistant11386.local
2024-11-19 15:00:45.812 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11386\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN TXT ""
2024-11-19 15:00:45.812 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11386.local IN A 192.168.10.247
2024-11-19 15:00:45.812 homeassistant systemd-resolved[416]: Hostname conflict, changing published hostname from 'homeassistant11386' to 'homeassistant11395'.
2024-11-19 15:00:45.957 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11395\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN TXT ""
2024-11-19 15:00:45.957 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11395\032\091431cf3e1addd46f5b14185b1bea39b0e\093._workstation._tcp.local IN SRV 0 0 0 homeassistant11395.local
2024-11-19 15:00:45.957 homeassistant systemd-resolved[416]: Detected conflict on homeassistant11395.local IN A 192.168.10.247
202
```

## System Information

version | core-2024.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | America/Toronto
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1536
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 205.1 GB
disk_used | 52.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | oracle
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Terminal & SSH (9.15.0), Mosquitto broker (6.4.1), AppDaemon (0.16.7), SQLite Web (4.2.2), Z-Wave JS (0.9.0), ESPHome (2024.10.3), phpMyAdmin (0.10.0), rtl_433 MQTT Auto Discovery (0.8.2), Samba share (12.3.2), Z-Wave JS UI (3.17.0), MariaDB (2.7.1), Zigbee2MQTT (1.41.0-1), MQTT Explorer (browser-1.0.3), Node-RED (18.1.1), Studio Code Server (5.17.3), Frigate Proxy (1.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 1
error | /config/ui-lovelace.yaml not found
views | 20
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 24, 2024 at 5:20 PM
-- | --
current_recorder_run | November 19, 2024 at 9:47 AM
estimated_db_size | 3032.83 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Supervisor diagnostics

[config_entry-hassio-5dae251bf6ea118d92a240060ae3caf8.json](https://github.com/user-attachments/files/17817802/config_entry-hassio-5dae251bf6ea118d92a240060ae3caf8.json)

### Additional information

In the meantime, I am trying the solution proposed in the following comment
https://github.com/home-assistant/operating-system/issues/1163#issuecomment-1817014802

Which for me was as follow, while connected through ssh.

1- List all connections
```
> nmcli -m tabular c


NAME               UUID                                  TYPE      DEVICE
Supervisor enp0s3  502849d7-2609-3319-813c-1622970139ef  ethernet  enp0s3
lo                 d5b4fc51-dc86-4e86-99d4-b9652b9b3f59  loopback  lo
```

2- Set mdns mode to resolve on the Supervisor connection
`> nmcli connection modify "Supervisor enp0s3" connection.mdns resolve`

3- Restart Network Manager
`> systemctl restart NetworkManager.service`

4- Confirm it works
```
> resolvectl mdns
Global: yes
Link 2 (enp0s3): resolve
Link 3 (docker0): yes
Link 4 (hassio): yes
```

I am wondering if this is something that could be exposed to the UI, or if someone has a better solution?

**Comment by sle118** [comment]
I ended up creating a custom add-on for this. It monitors the primary interface at regular (configurable interval) and if mdns is not "resolve" on the primary (configurable too) interface, then it changes mdns automatically. If anyone is interested, I'm willing to share but at least for now this will do the trick.

**Comment by skorpion1298** [comment]
Hey there :) I stumbled on this Thread here because my HA is using 30% CPU constantly and I was searching for a reason why. After scrolling through Logs I saw the Spamming of Hostname Conflicts. Can this be related to the CPU usage? If yes, I absolute would love to have your Add-On for this. High CPU Usage means High Electricity costs and here in Germany its expensive :D

Thank you a lot!

**Comment by agners** [comment]
> The default NetworkManager configuration sets mDNS to `yes` which, in network having multiple vlans and a reflector (e.g. on a Unifi network), result in a flood of mDNS requests originating from the supervisor's systemd-resolved.

> [...]

> The issue was also reported under the operating system project, but got closed. 

Just to be clear, from what I can tell,  the mDNS responder systemd-resolved behaves exactly how it is designed to behave: It uses the link-local mDNS protocol to announce its hostname, and validates the uniqueness on the network. The mDNS protocol is clearly defined as link-local only in [RFC6762](https://datatracker.ietf.org/doc/html/rfc6762). Handling name conflicts is not explicitly specified, but mentioned too as possible behavior.

The "issue" here is that mDNS reflectors are a hack to extend mDNS outside of the link-local context. This is operating mDNS clearly outside of the specified context! I am not aware of a RFC which would define mDNS reflector behavior, and how a multi-homed host should behave in the face of looped back mDNS announcements.

FWIW, mDNS reflector also do not work if a device has IPv6 link-local addressing (`fe80...`). These addresses do not work across network segments by design. I haven't looked into specific mDNS reflectors behavior, if there routable address classes in teh same respond, a mDNS reflector should at least filter out those link-local ones. Otherwise a resolving host might pick an address which is not valid in the local network segment. I just want to point out that this potentially lead to issues also in other use cases (e.g. Matter), since mDNS is expected to be link-local. 

That said, I understand that such Unifi network setups are quite popular. If folks feel comfortable to run mDNS in an non-standardized setup and deal with potential fallout (like this, I guess :see_no_evil: ) I am fine adding features to help make Home Assistant work in such environments.

Also keep in mind that you ask for a specific behavior which suits your specific network setup. I use VLANs as well, but without mDNS reflectors. I actually want Home Assistant to announce itself on every network.

**Comment by agners** [comment]
Btw, at least at one point Core itself also didn't like duplicate mDNS instances (see https://github.com/home-assistant/core/issues/50695). Now I think today this no longer leads to a packet flood, but there is probably still an error in the logs in these setups.

**Comment by agners** [comment]
> I am fine with turning off the reflector and keep all the esphome devices on the IoT VLAN, but I am not sure about other possible issues this could bring. For instance, how do you have home assistant "announce itself on every network"?

Yeah I think Home Assistant (the service) announces itself only on the primary interface currently. But since I have my phones etc. on the primary interface for me that is fine.

**Comment by patienttruth** [comment]
> I ended up creating a custom add-on for this. It monitors the primary interface at regular (configurable interval) and if mdns is not "resolve" on the primary (configurable too) interface, then it changes mdns automatically. If anyone is interested, I'm willing to share but at least for now this will do the trick.

If you'd be willing to share that would be awesome. I get it's a bandaid, but right now I'm just trying to keep everything stable until a better options comes. (thanks for the quick PR - I wish I knew how to make something like that happen so quickly!)

I'm also open to other solutions. Right now I have an IOT VLAN (no egress for most devices via firewall rules) and a Chromecast VLAN, as well as my main VLAN. HAOS sits on IOT and Main. Perhaps I could turn off mDNS on my Unifi USG, and put HAOS on the Chromecast VLAN as well. I haven't experimented with that, and only understand mDNS a little.

Ultimately my goal is segregated network for the IOT devices, and everything to work.

**Comment by Stan-Gobien** [comment]
I have the same setup with HA on normal LAN and second interface on IOT VLAN.
The mDNS names are used frequently in HA, and when you can't use them or click on them it's frustrating (because your computer is in the normal LAN). Example ESPhome shows the mDNS name and not the IP address. 

mDNS reflector/repeater was the solution, but triggered the above mentioned problem.

I'm interested in the add-on too, so I could use mDNS again.

**Comment by patienttruth** [comment]
> > I ended up creating a custom add-on for this.
> 
> If you'd be willing to share that would be awesome.

I went ahead and blocked mDNS on all except my main HOAS network interface via my router. No more log overload.

**Comment by sle118** [comment]
We should monitor https://github.com/home-assistant/supervisor/pull/5455

In the meantime, I went on a learning journey and created the following addon for anyone to use as a duck tape solution
https://github.com/sle118/addons-network-manager-fix

**Comment by patienttruth** [comment]
> We should monitor https://github.com/home-assistant/supervisor/pull/5455
> 
> In the meantime, I went on a learning journey and created the following addon for anyone to use as a duck tape solution
> https://github.com/sle118/addons-network-manager-fix
> 
> EDIT: Hold on with the installation please. It looks like I need to resolve a couple of issues with the published version;  local was just fine
> 

Thank you! Will hold tight for now.

**Comment by sle118** [comment]
ok Fixed. You can try now. The logs should output something like this: 

```
 Add-on: NetworkManager Fix
 Fix NetworkManager configuration for mDNS to prevent flooding caused by reflectors across multiple vlans
-----------------------------------------------------------
 Add-on version: 1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (amd64 / qemux86-64)
 Home Assistant Core: 2024.11.2
 Home Assistant Supervisor: 2024.11.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service nmfix: starting
s6-rc: info: service nmfix successfully started
s6-rc: info: service legacy-services: starting
[Warning]: apparmor not available on host system!
No log_level set in config, fallback to info
s6-rc: info: service legacy-services successfully started
Warning: nmcli (1.44.4) and NetworkManager (1.44.2) versions don't match. Restarting NetworkManager is advised.
[12:10:39] INFO: If different than the primary interface, please configure a primary interface from the following list:
[12:10:39] INFO: "Supervisor enp0s3"
[12:10:39] INFO: "lo"
[12:10:39] INFO: Primary adapter automatically detected: enp0s3. Getting connection name...
[12:10:39] INFO: Primary interface automatically detected: Supervisor enp0s3
[12:10:39] INFO: Current mDNS status for enp0s3 (Supervisor enp0s3): resolve
[12:10:39] INFO: no changes needed for enp0s3 (Supervisor enp0s3)
```

hope this will help someone while a real fix is being worked on

**Comment by coesy** [comment]
This is great, I've just started using this to reduce the noise in the logs. How do you configure a primary interface to use?

**Comment by sle118** [comment]
> This is great, I've just started using this to reduce the noise in the logs. How do you configure a primary interface to use?

By default, the add-on binds to the primary interface. You can check the documentation on the add-on where everything is explained as I could

**Comment by arsenicks** [comment]
Just to add to this, I'm ha ving the same issue using opnsense and mdns repeater. Will try the add on provided but I feel hass should really clear things regarding the current state of support for multi nic, there's problem that seems to be around for some time, like this one or the "default" network interface flapping between those available even if you select only one of the interface the supervisor can select another one and from my experience this can change..

**Comment by patienttruth** [comment]
> the current state of support for multi nic, there's problem that seems to be around for some time, like this one or the "default" network interface flapping between those available even if you select only one of the interface the supervisor can select another one and from my experience this can change..

I've noticed this too. I haven't concluded that it is causing a problem, although the only time I notice is when I'm into troubleshoot something networking related. It usually seems to sort itself out and assign the correct interface as "default", but it seems like that should be able to be manually defined.

I've also noticed that even though I disable a network interface in the HA settings, it will become re-enabled at some point. (Just checked, and my third interface is set to automatic again when I am certain I said it too disabled a couple days ago - perhaps it happens when I do a reboot).

**Comment by yiskang** [comment]
Please keep it up as the issue persists.

**Comment by bdraco** [comment]
It looks like core can't see the mDNS A record for `homeassistant.local.` and only previously worked because it was resolvable via a standard DNS query which is why we see https://github.com/home-assistant/core/issues/136922 in 2025.2 beta

[browse_workstation.py.zip](https://github.com/user-attachments/files/18605851/browse_workstation.py.zip)

**Comment by agners** [comment]
@bdraco this issue is about a very particular setup:

- Home Assistant is multi-homed
- The two networks Home Assistant is in are "connected" with a mDNS reflector. That leads to mDNS packets sent out on one interface received on the other.
- This particular setup leads to systemd-resolved's conflict handling to trigger: If it detects the same hostname on the network, it starts to increment the hostname.

systemd-resolved just does not expect to receive it's own announcement (which IMHO is a very sane assumption, since mDNS is supposed to stay within a network, and not carried across network).

Now, for that particular setup, there is a easy solution: We can just ask systemd-resolved to not use mDNS on one of the two interfaces.

However, you seem to point to a different issue: Home Assistant Core conflicting with systemd-resolved? Not sure if this is a new problem. In general, I expect the operating system to be owner of the actual hostname (systemd-resolved). This makes mDNS resolving also work early at bootup and before Core is downloaded (landing page). In any case, if there is something we need to change in Supervisor, let's discuss this in a new/separate issue.

**Comment by Depechie** [comment]
Hey @agners just for completeness, the solution that you describe "_We can just ask systemd-resolved to not use mDNS on one of the two interfaces._" is there a guide on how to do this with an Unifi setup?
Because for now I personally just disabled mDNS on my VLAN to avoid the problem, which works but if I read your comment, I guess I would not need to do this, but somehow change a setting on the secondary network interface on my Home Assistant?

**Comment by Stan-Gobien** [comment]
> I guess I would not need to do this, but somehow change a setting on the secondary network interface on my Home Assistant?

That's exactly what the above referenced addon does
https://github.com/sle118/addons-network-manager-fix

**Comment by agners** [comment]
> Hey [@agners](https://github.com/agners) just for completeness, the solution that you describe "_We can just ask systemd-resolved to not use mDNS on one of the two interfaces._" is there a guide on how to do this with an Unifi setup?

Yeah sorry, that is not implemented yet. The add-on is a work around, but PR https://github.com/home-assistant/supervisor/pull/5520 tries to address that by adding new interface settings on Supervisor level.

**Comment by mundschenk-at** [comment]
This issue is still present.

**Comment by hannorein** [comment]
In my case the mDNS hostname conflicts (and the resulting high CPU usage) were due to a misconfiguration of my container setup. Obvious (and stupid) in retrospect, but it took me ages to find out that it has nothing to do with any mDNS reflector. So I'm putting it here in case someone else finds this helpful.

In my case, the container I use for HA had still the default user-mode network interface (for NAT) as well as a bridged one which I manually added. Clearly not the right way to configure it but it didn't lead to any issues except with the HA's mDNS packages which got re-routed back to itself over the second network interface, hence leading to all the conflicts.

**Comment by mmerickel** [comment]
A couple notes as I've run into this on my network as well when multi-homing HA within proxmox on 2 VLANs. In proxmox I configured 2 separate network adapters and tagged them to VLANs within there, so HA does not know about that config. It just sees 2 network adapters (possibly why the default route issue exists below?).

1. I had to setup custom NetworkManager configs for each interface so that I could turn off default routes on the secondary interface. I used this to set `ipv4.ignore-auto-routes=yes` and `ipv4.ignore-auto-dns=yes`, and same for ipv6. This works fine, survives reboots, etc. Unfortunately this seemed to be the only option because even trying to set the secondary interface as static wouldn't allow me to turn off the gateway in the HA UI at HA -> Settings -> System -> Network -> ENS0P19 -> Static Configuration -> Gateway.
2. I tried to modify these configs to have `connection.mdns=1` to switch it to resolve, but no matter what something keeps overwriting the settings on reboot. I think it's something in supervisor but I haven't tried to pin it down.
3. To get around this I used `chattr +i /etc/NetworkManager/system-connections/ens0p19.nmconnection` (the file I created in step 1 for the secondary interface) and now it properly survives a reboot. Awful hack but this is working for me.

My expectation as a naive user was that the already-existing HA setting would have handled this for me. It's worded as such, and I can't tell what it does otherwise, but it isn't solving either problem 1) do not register the secondary interfaces as a default route and 2) do not announce mdns on the secondary interfaces. The setting I'm referring to is HA -> Settings -> System -> Network -> Network Adapter where it says `Configure which network adapters integrations will use. Currently this setting only affects multicast traffic. A restart is required for these settings to apply.`. Contrary to the wording I do not see how it affects multicast traffic but I'm sure I'm reading it wrong.

Anyway, take it how you will but this is what I had to do right now to fix things.

**Comment by Stan-Gobien** [comment]
You can change the metric on the default route for the interface.
See:
https://community.home-assistant.io/t/hassos-with-multiple-network-cards/170081/12

Higher metric number means lower priority.
This works and persists.

**Comment by mmerickel** [comment]
not stale

**Comment by mundschenk-at** [comment]
not stale

**Comment by fireheadman** [comment]
not stale... 

I have 2 network interfaces.
changed the hostname, that persists.

only change was migrating to HAOS from debian build.
host log is spewing like crazy!

**Comment by digital-pet** [comment]
I have this issue with two interfaces on different vlans, similar to the proxmox setup described above, and no mDNS reflection.

**Comment by a10kiloham** [comment]
thanks to @sle118 for that add-on! worked perfectly to patch this for the while.

**Comment by cmatte** [comment]
Not stale.

**Comment by a10kiloham** [comment]
Not stale still a consequential problem.

**Comment by digitalresistor** [comment]
Bad stale bot is bad.

**Comment by Bandit** [comment]
Also getting this error

**Comment by digital-pet** [comment]
having the stale bot run monthly is absurd lol

**Comment by MaxGrmm** [comment]
Same issue here!

**Comment by a10kiloham** [comment]
Yah me as well I am already emotional about the new Taylor swift album so I can call me above ground and have a chance that is a big reward!!!!!!!!

**Comment by fcy** [comment]
I'm also hitting this issue, I've arrived here after stumbling upon the unbelievable crazy amount of logs from my host. It spews around 30 message per second!

**Comment by t3hk0d3** [comment]
🤞🏻 for the next supervisor release.
Should be possible to change it using CLI (https://github.com/home-assistant/cli/pull/591).
I'll work on introducing controls to hass-frontend as well.

**Comment by t3hk0d3** [comment]
Supervisor version `2025.09.0` has been released today.
Unfortunately there is currently no way to change `mdns` mode using normal means:
- PR for CLI (https://github.com/home-assistant/cli/pull/591) has been merged, but new version haven't been released yet.
- Changes for HA frontend are still WIP.
- You can try to make an Supervisor API calls yourself, but that's a bit complicated because of authentication.

However!
Changing values in NM cli should work now, since Supervisor will respect whatever value is configured in Network Manager:

```
# nmcli c show --active # show active connection
# nmcli c modify "Supervisor eth0" connection.mdns 1 # change mdns mode to resolve
```

**Comment by fcy** [comment]
I ended up calling Supervisor API directly 🙈 I really didn't want to do all the changes to get to nmcli on my instance, it was ok to do with Terminal & SSH Add-On (and some AI to figure out the API calls were). Example of my network:

```
# Find your interfaces and current state
curl -sS -H "Authorization: Bearer $SUPERVISOR_TOKEN" http://supervisor/network/info | jq .

# MGMT: resolve-only, no LLMNR
curl -sS -X POST \
  -H "Authorization: Bearer $SUPERVISOR_TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"mdns":"resolve","llmnr":"off"}' \
  http://supervisor/network/interface/end0/update

# IoT: advertise & resolve, no LLMNR
curl -sS -X POST \
  -H "Authorization: Bearer $SUPERVISOR_TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"mdns":"announce","llmnr":"off"}' \
  http://supervisor/network/interface/end0.3/update
```

**Comment by Mvanmierlo** [comment]
Just went into my logs due to another issue and found this MDNS issue too ..Not sure why it is closed as the bug is still pressent

**Comment by agners** [comment]
> Not sure why it is closed as the bug is still pressent

Detecting mDNS conflicts is _not_ a bug, its a feature which works well in any correctly configured network.

However, using mDNS reflector can cause conflict detection to fire extensively. But that is because you operate mDNS in a way which it never was intended to be run 🤷 .

You are free to do so, but this is not a bug in the software.

However, you have the option to disable mDNS announcement, but just like mDNS reflectors, you need to configure Home Assistant to _not_ announce mDNS on both networks you are using mDNS reflectors in between. The latest Terminal & SSH add-on (9.20.0) has the necessary CLI tools, disable announcement on one of the two interfaces, e.g.:

```
ha network update enp7s0 --mdns resolve --llmnr off
ha network update enp7s0.10 --mdns announce --llmnr off
```

**Comment by cmatte** [comment]
@agners or @t3hk0d3 - thanks a lot for tracking on this and for developing a viable solution. Wondering why the above @agners suggests setting llmnr to off rather than the same pair of resolve/announce, which would logically click with the same mDNS settings, i.e. typically I'd be biased to set the above as below.
```
ha network update enp7s0 --mdns resolve --llmnr resolve
ha network update enp7s0.10 --mdns announce --llmnr announce
```

May I check if we are aware of any effect of LLMNR protocol from a HA/OS, Matter, OTBR point of view, similar to mDNS creating the flooding changes of hostname for HA in a Ubiquiti gateway environment with enabled mDNS reflector, but happening with LLMNR?

**Comment by t3hk0d3** [comment]
@cmatte 
LLMNR protocol has much more limited use, and having it enabled without actual need feels wasteful. Although i assume @agners shared just an example rather than recommendation.

**Comment by agners** [comment]
> Although i assume [@agners](https://github.com/agners) shared just an example rather than recommendation.

Right. For a while LLMNR was the only multicast based name resolving solution on Windows. But sometime in the Windows 10 days Windows got native mDNS support, since then it has less of an importance.

**Comment by cmatte** [comment]
Thanks both, that clarifies indeed, glad that the assumption that there is a technical requirement reason to keep LLMNR on by default was just historical rather than applicable to modern days. It may be worth considering changing its default settings too, basis the same series of thoughts.

**Comment by agners** [comment]
Hm, it seems it is being discussed in upstream systemd at https://github.com/systemd/systemd/pull/28263#issuecomment-2486626786. I'd just wait until upstream systemd merges that change and trickles down to HAOS. Afaik, so far it seems not to have downsides on our end.

**Comment by cmatte** [comment]
Got it, makes perfect sense 😉 Thanks both for the insights. In fact the attached even mentions a possible racing condition between LLMNR and DNS, weighing on the suggestion of disabling it to avoid that, especially in multi homed environments.

**Comment by agners** [comment]
There is a bug report in upstream systemd related to this conflict detection: https://github.com/systemd/systemd/issues/35780

Disabling mDNS announcement on one of the interfaces is still a good/clean fix to avoid spurious conflict detection.
